# Generated by Django 4.2.13 on 2026-05-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatmessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='verified_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
